#####string operators
# in , not in, +, *
'TATA' in 'TATATATATATATATATATATA'
#True
'AA' in 'TATATATATATATATATATATA'
#False
'AA' not in 'TATATATATATATATATATATATA'
#True

# concatenation is done by +
'AC' + 'TG'
'aaa' + 'ccc' + 'ttt' + 'ggg'

#repeating a string
'TA' * 12
6 * 'TA'

#####Subscription
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[0]
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[1]
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[−1]
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[−5]
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[7 // 2]

#####Slicing
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[1:4]
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[4:-1]
'MNKMDLVADVAEKTDLSKAKATEVIDAVFA'[-5:-4]